name: isolates_helper
description: "Creates multiple long-lived isolates to compute multiple functions; Supports Worker and WASM on the Web; Supports try-catch block"
version: 0.4.3+1
homepage: https://github.com/lamnhan066/isolates_helper

environment:
  sdk: "^3.3.0"

dependencies:
  isolate_manager: ^5.0.0-rc.2

dev_dependencies:
  test: ^1.24.4
  lints: ^2.1.1
