name: isolates_helper
description: "An easy way to create multiple long live isolates to compute multiple functions, support Worker on the Web and try-catch block"
version: 0.4.2
homepage: https://github.com/lamnhan066/isolates_helper

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  isolate_manager: ^4.2.2

dev_dependencies:
  test: ^1.24.4
  lints: ^2.1.1
